module.exports = [
    {city: "San Francisco",state:"California"},
    {city:"San Jose", state:"California"},
    {city:"Inverness", state: "California"},
    {city: "Sausalito", state:"California"},
    {city: "San Mateo", state: "California"},
    {city:"Santa Rosa", state:"California"},
    {city: "Los Angeles", state:"California"},
    {city:"San Diego", state:"California"},
    {city:"Santa Barbara", state:"California"},
    {city:"Fort Bragg", state:"California"},
    {city:"Eureka", state:"California"},
    {city:"Sacramento", state:"California"},
    {city:"Tahoe City", state:"California"},
    {city:"Mariposa", state:"California"},
    {city:"Crescent City", state:"California"},
    {city:"Davenport", state:"California"},
    {city:"Santa Cruz", state:"California"},
    {city:"Redding", state:"California"},
    {city:"Willows", state:"California"},
    {city:"Chico", state:"California"},
    {city:"Clearlake", state:"California"},
    {city:"Healdsburg",state:"California"},
    {city:"Monterey", state:"California"},
    {city:"Cambria", state:"California"},
    {city:"Morro Bay", state:"California"},
    {city:"Oxnard", state:"California"},
    {city:"Thousand Oaks", state:"California"},
    {city:"Chico", state:"California"},
    {city:"Yuba City", state:"California"},
    {city:"Walnut Creek", state:"California"},
    {city:"Stockton", state:"California"},
    {city:"Paicines", state:"California"},
    {city:"Hollister", state:"California"},
    {city:"Petaluma", state:"California"}
]